version: '3.8'

services:
  app:
    build: .
    container_name: rest-api-cw-app
    ports:
      - "5000:5000"
    volumes:
      - ./app/utils/countries_api.db:/usr/src/app/app/utils/countries_api.db
    environment:
      - PYTHONUNBUFFERED=1